[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
    "aa/=node_modules/aa/contracts/",
    "model/=lib/model/",
    "@openzeppelin/=node_modules/@openzeppelin/",
] # See more config options https://github.com/foundry-rs/foundry/tree/master/config
